- name: Сбор информации
  hosts: servers
  become: yes
  tasks:
  - name: Сбор IP-адреса
    shell: hostname -I | awk '{print $1}'
    register: ip_address
  - name: Сбор версии ОС
    shell: cat /etc/os-release | grep "PRETTY_NAME" | cut -d '"' -f 2
    register: os_version
  - name: Сбор имени хоста
    shell: hostname
    register: hostname
  - name: Сбор свободного места на диске
    shell: df -h / | awk 'NR==2 {print $4}'
    register: disk_space
  - name: Сохранение информации в файл
    delegate_to: localhost
    become: yes
    copy:
      content: |
        IP: {{ ip_address.stdout }}
        OS: {{ os_version.stdout }}
        Hostname: {{ hostname.stdout }}
        Free Disk Space: {{ disk_space.stdout }}
        dest: /etc/ansible/IT-Planet/{{ inventory_hostname }}.txt
